version: 2
sources:
- name: kiotviet
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_invoices_airbytestorage
  - name: _airbyte_raw_invoices_fullload_airbytestorage