config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
kiotviet:
  outputs:
    prod:
      dbname: stagging
      host: localhost
      pass: docker
      port: 5432
      schema: kiotviet
      threads: 8
      type: postgres
      user: docker
  target: prod
